Minor formatting cleanup in kiva compiled path
enthought/enable pull request #783
Opened 2021-04-19 03:09 UTC by rahulporuri

2021-04-19 20:32 UTC, aaronayres35 requested changes
It looks like every changed line is now under indented by one level.
In fact the indentation looks correct on master for me, I am not sure what is going on here

2021-04-19 20:32 UTC, aaronayres35 commented on kiva/agg/src/kiva_compiled_path.h
> +	 to vertices added to the path.
This appears to be under indented for me now

2021-04-19 20:32 UTC, aaronayres35 commented on kiva/agg/src/kiva_compiled_path.h
> +	 Todo: Should this default to the identity matrix or the current ctm?
same with the above hack... and todo comments

2021-04-20 14:50 UTC, aaronayres35 reviewed
These now look correctly aligned on github, but when i checkout the branch and view the file on VS Code things are under indented / off.  On master things look correctly aligned for me locally in VSCode...

2021-04-20 15:00 UTC, rahulporuri commented
im just going to close this. this might just be something wonky on github or maybe its spaces vs tabs or i dont know wth.

2021-04-20 15:00 UTC, closed without merging